FROM node:16 as build-deps
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn
COPY . ./
RUN yarn run build:prod

FROM nginx:1.21.6-alpine
COPY --from=build-deps /app/dist /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/nginx.conf

RUN nginx -t

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]